### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by fragtion** [FrederikP/csgo-alltime-stats#1] opened 2018-12-09 10:01 UTC
Thanks for creating this utility
Just having some problems running it
1) for username and auth code, I had to manually put quotation marks ("") or it throws an error
2) after successful login, it shows AttributeError: 'NoneType' object has no attribute 'find_all':
```
root@server:/usr/local/src/csgo-alltime-stats# python fetch_stats.py
Enter user name: "myuser"
Enter password (will not be echoed):
Enter email auth code: "FKH2N"
Logged in!
Traceback (most recent call last):
  File "fetch_stats.py", line 222, in <module>
    tds = table.find_all('tr')[1].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find_all'
```

Python 2.7.15+ on Linux 4.18.0-12-generic, Ubuntu 18.10 cosmic

**Comment by FrederikP** [comment] 2018-12-09 10:59
Hi, I have only tested this with python 3. Can you try running this with python 3?Maybe I have some time to make it compatible in the future, but so far not a lot of people seemed interested, so it's far from polished currently.

**Comment by fragtion** [comment] 2018-12-09 11:32
Hey. Thanks for quick reply.

Tried with python3. It fixed the quotation marks issue with login, but same error while trying to retrieve stats

If I can fix it so long I will send a pull request

root@server:/usr/local/src/csgo-alltime-stats# pip3 install requests rsa beautifulsoup4 dotmap progressbar2 tinydb
Requirement already satisfied: requests in /usr/lib/python3/dist-packages
Collecting rsa
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting beautifulsoup4
  Downloading https://files.pythonhosted.org/packages/21/0a/47fdf541c97fd9b6a610cb5fd518175308a7cc60569962e776ac52420387/beautifulsoup4-4.6.3-py3-none-any.whl (90kB)
    100% |████████████████████████████████| 92kB 3.4MB/s
Collecting dotmap
  Downloading https://files.pythonhosted.org/packages/29/c3/28bc388c03d21422452b8150d2c24fe9715a0c31afe9b3d436ba6f899894/dotmap-1.3.4-py3-none-any.whl
Collecting progressbar2
  Using cached https://files.pythonhosted.org/packages/4f/6f/acb2dd76f2c77527584bd3a4c2509782bb35c481c610521fc3656de5a9e0/progressbar2-3.38.0-py2.py3-none-any.whl
Collecting tinydb
  Using cached https://files.pythonhosted.org/packages/58/55/54f428597853184ff74f6e65ff9c771aaad353fc182f881d9863bcc3bace/tinydb-3.12.1-py2.py3-none-any.whl
Requirement already satisfied: pyasn1>=0.1.3 in /usr/lib/python3/dist-packages (from rsa)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from progressbar2)
Collecting python-utils>=2.3.0 (from progressbar2)
  Using cached https://files.pythonhosted.org/packages/eb/a0/19119d8b7c05be49baf6c593f11c432d571b70d805f2fe94c0585e55e4c8/python_utils-2.3.0-py2.py3-none-any.whl
Installing collected packages: rsa, beautifulsoup4, dotmap, python-utils, progressbar2, tinydb
Successfully installed beautifulsoup4-4.6.3 dotmap-1.3.4 progressbar2-3.38.0 python-utils-2.3.0 rsa-4.0 tinydb-3.12.1
root@pappasfw:/usr/local/src/csgo-alltime-stats# python3 fetch_stats.py
Enter user name: myuser
Enter password (will not be echoed):
Enter email auth code: M8HX8
Logged in!
Traceback (most recent call last):
  File "fetch_stats.py", line 222, in <module>
    tds = table.find_all('tr')[1].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find_all'
root@server:/usr/local/src/csgo-alltime-stats#

**Comment by FrederikP** [comment] 2018-12-09 11:47
Okay, good find. Not currently at my pc, but probably they changed their html page then. I don't know why they don't just offer this data through their api anyway... You most likely have to change the beautiful soup html parsing stuff. If you get that running, I'll gladly merge the PR. If not I'll have a look next week

**Comment by FrederikP** [comment] 2018-12-10 12:49
I realized I had some unpushed local changes. I just pushed those and also tried running:

```
python fetch_stats.py
python aggregate_stats.py
python check_bans.py 
```

Everything ran without issues for me. Can you try latest master? If something still doesn't work I can have a look after work today.

**Comment by FrederikP** [comment] 2019-01-02 09:14
@fragtion have you had a chance to try?

**Comment by fragtion** [comment] 2019-01-03 14:13
> @fragtion have you had a chance to try?
Hey @FrederikP 

I tried latest master & got same error unfortunately -

root@server:/tmp/stats# python3 fetch_stats.py
Enter steam api key (get it at  https://steamcommunity.com/dev/apikey): <HIDDEN>
Enter user name: dimitripappas
Enter password (will not be echoed):
Enter email auth code: 6GNWJ
Logged in!
Traceback (most recent call last):
  File "fetch_stats.py", line 38, in <module>
    tds = table.find_all('tr')[1].find_all('td')
AttributeError: 'NoneType' object has no attribute 'find_all'
root@server:/tmp/stats#

I've noticed two things in my own debugging thus far.  Firstly, redirects for initial request should be allowed I think? In my case I received no HTML for the get request unless changing fetch_stats.py as follows:
```
-response = requests.get(count_url, headers=headers, allow_redirects=False)
+response = requests.get(count_url, headers=headers, allow_redirects=True)
```
Afterwards, you see it follows the 302 redirects:
302 https://steamcommunity.com/profiles/76561197990921651/gcpd/730/?tab=matchmaking
302 https://steamcommunity.com/id/fragtion/gcpd/730?tab=matchmaking
Final destination:
200 https://steamcommunity.com/id/fragtion

Unfortunately however, I still get the same error and have not had a chance to check the BeautifulSoup parsing yet myself.  I've enabled print of the soup variable for debugging, and captured the stdout to pastebin if you are interested: 
https://pastebin.com/1THFg4M9

What do you think ?:)

**Comment by FrederikP** [comment] 2019-01-03 14:27
Okay thanks for the detailed answer.

I'm not sure why you are being redirected by steam here.
For me the script still works as of today and allowing redirects will not help you.

What happenes when you login to steam in the browser and then go to the matchmaking url? Are you also redirected?

Edit: For me the redirects happen, when I'm trying to look at the matchmaking page for a different profile id. But it should work when logged in with the right user. Maybe something is wrong with the way I resolve the profile id.

**Comment by fragtion** [comment] 2019-01-03 14:34
> What happenes when you login to steam in the browser and then go to the matchmaking url? Are you also redirected?

It only redirects to https://steamcommunity.com/id/fragtion/gcpd/730?tab=matchmaking, where I can see the stats overview. It doesn't reach https://steamcommunity.com/id/fragtion
Using Chrome on Win10

**Comment by FrederikP** [comment] 2019-01-03 14:36
> > What happenes when you login to steam in the browser and then go to the matchmaking url? Are you also redirected?
> 
> No. Stays at https://steamcommunity.com/id/fragtion/gcpd/730?tab=matchmaking , where I can see the stats overview as expected, so I think you are right about that

Interesting. So it doesn't use the profile id (as it does for me), but your alias. So your profile is probably different from mine in that sense. I'll come up with some sort of distinction to fix this.

**Comment by FrederikP** [comment] 2019-01-03 14:44
Was able to reproduce this by setting a custom URL for my own account. So I'll fix that. Shouldn't take too long.

**Comment by FrederikP** [comment] 2019-01-03 14:58
@fragtion please retry with latest master

**Comment by fragtion** [comment] 2019-01-03 15:10
Loading 2163 matches (975 won, 187 tied, 1001 lost)
  0% (2 of 2163) |                                                                                                                                                                                    | Elapsed Time: 0:00:05 ETA:   1:30:46

Working now! Can't wait to play around with the db.  Will keep you updated if I run into any other issues :) Thank you. ^5

**Comment by FrederikP** [comment] 2019-01-03 15:14
You are welcome. Thanks for trying. If you create something cool, be sure to let me know and maybe create a pull request. Did not have a ton of time to work on this, but there is some potential I think.

Sorry that it takes so long, but it is building a user DB on the first run. As long as you don't delete the `csgo-alltime-stats.db`  it won't do it again. The reason for this is that I wanted to implement the ban checking stuff without needing to query simple user stuff from the match data again and again. Closing this issue now.

**Closed as completed by FrederikP** 2019-01-03 15:14 UTC
